const viewport=document.getElementById('viewport');
const loading=document.getElementById('loading');
const scene=new THREE.Scene();
scene.background=new THREE.Color(0x02030a);
scene.fog=new THREE.FogExp2(0x02030a,0.00045);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,0.05,4000);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));
renderer.setSize(innerWidth,innerHeight);
renderer.outputEncoding=THREE.sRGBEncoding;
viewport.appendChild(renderer.domElement);
scene.add(new THREE.AmbientLight(0x7782ad,0.24));
const sunLight=new THREE.PointLight(0xffe5bd,5,800);scene.add(sunLight);
const state={paused:false,speed:1,labels:true,mode:'solar',selected:null,follow:false,yaw:.7,pitch:.3,distance:55,target:new THREE.Vector3(),drag:false,lastX:0,lastY:0};
const objects=[],labels=[],orbits=[],discovered=new Set();
function texture(type){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');const colors={sun:'#e99b20',mercury:'#77746d',venus:'#b97835',earth:'#165a9c',mars:'#783526',jupiter:'#ad835d',saturn:'#c2aa78',uranus:'#55aeb9',neptune:'#294c9c',moon:'#777'};x.fillStyle=colors[type]||'#777';x.fillRect(0,0,512,256);if(type==='earth'){for(let i=0;i<55;i++){x.fillStyle=i%5?'#39794b':'#9b8c54';x.beginPath();x.ellipse(Math.random()*512,25+Math.random()*205,8+Math.random()*35,4+Math.random()*20,Math.random()*3.14,0,6.28);x.fill()}for(let i=0;i<30;i++){x.fillStyle='rgba(255,255,255,.13)';x.beginPath();x.ellipse(Math.random()*512,Math.random()*256,30+Math.random()*55,3+Math.random()*8,Math.random(),0,6.28);x.fill()}}if(['jupiter','saturn','uranus','neptune'].includes(type)){for(let i=0;i<90;i++){x.fillStyle=i%2?'rgba(255,235,195,.18)':'rgba(55,35,30,.2)';x.fillRect(0,Math.random()*256,512,5+Math.random()*24)}}if(['mars','moon','mercury'].includes(type)){for(let i=0;i<130;i++){x.fillStyle=i%2?'rgba(30,25,25,.2)':'rgba(240,240,240,.09)';x.beginPath();x.arc(Math.random()*512,Math.random()*256,1+Math.random()*9,0,6.28);x.fill()}}if(type==='venus'){for(let i=0;i<45;i++){x.strokeStyle='rgba(255,220,140,.18)';x.lineWidth=2+Math.random()*6;x.beginPath();x.moveTo(0,Math.random()*256);x.bezierCurveTo(170,Math.random()*256,340,Math.random()*256,512,Math.random()*256);x.stroke()}}for(let i=0;i<1300;i++){x.fillStyle='rgba(255,255,255,'+(Math.random()*.045)+')';x.fillRect(Math.random()*512,Math.random()*256,1,1)}return new THREE.CanvasTexture(c)}
function bump(){const c=document.createElement('canvas');c.width=256;c.height=128;const x=c.getContext('2d');x.fillStyle='#777';x.fillRect(0,0,256,128);for(let i=0;i<500;i++){const v=70+Math.random()*170;x.fillStyle=`rgb(${v},${v},${v})`;x.beginPath();x.arc(Math.random()*256,Math.random()*128,Math.random()*4,0,6.28);x.fill()}return new THREE.CanvasTexture(c)}
function glow(size,color){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'#fff');g.addColorStop(.12,color);g.addColorStop(.45,color+'55');g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,128,128);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));s.scale.set(size,size,1);scene.add(s);return s}
function stars(count,radius,color,size,opacity,flat){const g=new THREE.BufferGeometry(),p=new Float32Array(count*3);for(let i=0;i<count;i++){const r=radius*(.15+Math.random()*.85),a=Math.random()*6.28,b=Math.acos(2*Math.random()-1);p[i*3]=r*Math.sin(b)*Math.cos(a);p[i*3+1]=flat?(Math.random()-.5)*radius*.035:r*Math.cos(b);p[i*3+2]=r*Math.sin(b)*Math.sin(a)}g.setAttribute('position',new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color,size,transparent:true,opacity,sizeAttenuation:true}))}
scene.add(stars(18000,1200,0xbcc8ff,.7,.9,false));const galaxy=stars(11000,500,0x6879ff,.6,.2,true);scene.add(galaxy);const dust=stars(5000,220,0x8a76ff,.6,.13,true);scene.add(dust);
const sun=new THREE.Mesh(new THREE.SphereGeometry(3.7,48,32),new THREE.MeshBasicMaterial({map:texture('sun')}));sun.userData={name:'Sol',type:'Estrela',scale:'1.39 milhões km',desc:'A estrela no centro do Sistema Solar.'};scene.add(sun);objects.push(sun);const sunGlow=glow(18,'#ffb32e');
const data=[['Mercúrio',6.2,.5,'mercury',.018,'Planeta rochoso','4.879 km','O menor planeta e o mais próximo do Sol.'],['Vênus',8.7,.85,'venus',.014,'Planeta rochoso','12.104 km','Um mundo quente coberto por uma atmosfera densa.'],['Terra',11.8,.95,'earth',.011,'Planeta rochoso','12.742 km','Nosso planeta, lar da vida conhecida.'],['Marte',15,.68,'mars',.009,'Planeta rochoso','6.779 km','O planeta vermelho com vulcões e antigos vales.'],['Júpiter',21,2.05,'jupiter',.006,'Gigante gasoso','139.820 km','O maior planeta do Sistema Solar.'],['Saturno',28,1.75,'saturn',.0048,'Gigante gasoso','116.460 km','Gigante gasoso com um sistema de anéis espetacular.'],['Urano',35,1.25,'uranus',.0038,'Gigante de gelo','50.724 km','Gigante de gelo com rotação extremamente inclinada.'],['Netuno',42,1.2,'neptune',.003,'Gigante de gelo','49.244 km','Planeta distante com ventos intensos.']];
function orbitLine(r){const pts=[];for(let i=0;i<=256;i++){const a=i/256*6.28;pts.push(new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r))}const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x65749f,transparent:true,opacity:.17}));scene.add(l);orbits.push(l)}
function makeLabel(text){const c=document.createElement('canvas');c.width=300;c.height=70;const x=c.getContext('2d');x.font='600 24px Arial';x.fillStyle='#fff';x.textAlign='center';x.fillText(text,150,43);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.scale.set(4.8,1.12,1);scene.add(s);labels.push(s);return s}
const planets=[];data.forEach(d=>{const [name,r,size,type,velocity,kind,scale,desc]=d;orbitLine(r);const material=new THREE.MeshStandardMaterial({map:texture(type),roughness:.9,bumpMap:['earth','mars','moon','mercury'].includes(type)?bump():null,bumpScale:.025});const p=new THREE.Mesh(new THREE.SphereGeometry(size,40,28),material);p.userData={name,type:kind,scale,desc,orbit:r,velocity,angle:Math.random()*6.28};scene.add(p);planets.push(p);objects.push(p);const l=makeLabel(name);l.userData.target=p;if(name==='Saturno'){const ring=new THREE.Mesh(new THREE.RingGeometry(2.35,4.15,96),new THREE.MeshStandardMaterial({map:texture('saturn'),side:THREE.DoubleSide,transparent:true,opacity:.8,roughness:1}));ring.scale.set(size/1.75,size/1.75,1);ring.rotation.x=Math.PI/2.25;p.add(ring)}});
const earth=planets[2];const moon=new THREE.Mesh(new THREE.SphereGeometry(.27,28,20),new THREE.MeshStandardMaterial({map:texture('moon'),roughness:1,bumpMap:bump(),bumpScale:.04}));moon.userData={name:'Lua',type:'Satélite natural',scale:'3.475 km',desc:'O satélite natural da Terra.'};scene.add(moon);objects.push(moon);const moonLabel=makeLabel('Lua');moonLabel.userData.target=moon;
const asteroidGeometry=new THREE.BufferGeometry(),asteroidPositions=new Float32Array(2200*3);for(let i=0;i<2200;i++){const a=Math.random()*6.28,r=16.5+Math.random()*3.2;asteroidPositions[i*3]=Math.cos(a)*r;asteroidPositions[i*3+1]=(Math.random()-.5)*1.1;asteroidPositions[i*3+2]=Math.sin(a)*r}asteroidGeometry.setAttribute('position',new THREE.BufferAttribute(asteroidPositions,3));const asteroidBelt=new THREE.Points(asteroidGeometry,new THREE.PointsMaterial({color:0xb7aaa0,size:.08}));scene.add(asteroidBelt);
const comet=new THREE.Mesh(new THREE.SphereGeometry(.28,20,16),new THREE.MeshBasicMaterial({color:0xdff6ff}));const cometGlow=glow(3.8,'#75d5ff');let cometAngle=0;scene.add(comet);comet.userData={name:'Cometa',type:'Corpo menor',scale:'variável',desc:'Um visitante gelado atravessando o sistema.'};objects.push(comet);const cometLabel=makeLabel('Cometa');cometLabel.userData.target=comet;
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
function select(obj){state.selected=obj;document.getElementById('objectName').textContent=obj.userData.name;document.getElementById('objectDesc').textContent=obj.userData.desc;document.getElementById('objectType').textContent=obj.userData.type;document.getElementById('objectScale').textContent=obj.userData.scale;document.getElementById('missionText').textContent=discovered.has(obj.userData.name)?'Descoberta registrada.':'Objeto detectado. Escaneie para registrar.'}
function reset(){state.target.set(0,0,0);state.yaw=.7;state.pitch=.3;state.distance=55;state.follow=false;document.getElementById('followObject').textContent='◎ Seguir objeto'}
function mode(name){state.mode=name;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));state.follow=false;if(name==='solar'){reset();[sun,...planets,moon,comet,asteroidBelt].forEach(o=>o.visible=true);orbits.forEach(o=>o.visible=true);sunGlow.visible=true}else if(name==='galaxy'){state.target.set(0,0,0);state.distance=230;state.pitch=1.05;[sun,...planets,moon,comet,asteroidBelt].forEach(o=>o.visible=false);orbits.forEach(o=>o.visible=false);sunGlow.visible=false}else{state.target.set(0,0,0);state.distance=420;state.pitch=.2;[sun,...planets,moon,comet,asteroidBelt].forEach(o=>o.visible=false);orbits.forEach(o=>o.visible=false);sunGlow.visible=false}}
function cameraUpdate(){const cp=Math.cos(state.pitch);camera.position.set(state.target.x+Math.sin(state.yaw)*cp*state.distance,state.target.y+Math.sin(state.pitch)*state.distance,state.target.z+Math.cos(state.yaw)*cp*state.distance);camera.lookAt(state.target)}
renderer.domElement.addEventListener('pointerdown',e=>{state.drag=true;state.lastX=e.clientX;state.lastY=e.clientY;mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(objects,false)[0];if(hit)select(hit.object)});addEventListener('pointermove',e=>{if(!state.drag)return;state.yaw-=(e.clientX-state.lastX)*.006;state.pitch=Math.max(-1.45,Math.min(1.45,state.pitch-(e.clientY-state.lastY)*.006));state.lastX=e.clientX;state.lastY=e.clientY});addEventListener('pointerup',()=>state.drag=false);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();state.distance=Math.max(4,Math.min(1100,state.distance*Math.exp(e.deltaY*.001)));},{passive:false});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>mode(b.dataset.view));document.getElementById('speed').oninput=e=>{state.speed=Number(e.target.value);document.getElementById('speedValue').textContent=state.speed.toFixed(1)+'×'};document.getElementById('toggleMotion').onclick=()=>{state.paused=!state.paused;document.getElementById('toggleMotion').textContent=state.paused?'▶ Continuar simulação':'Ⅱ Pausar simulação'};document.getElementById('resetCamera').onclick=()=>{mode('solar');select(sun)};document.getElementById('toggleLabels').onclick=()=>{state.labels=!state.labels;labels.forEach(l=>l.visible=state.labels)};document.getElementById('followObject').onclick=()=>{if(!state.selected)return;if(state.follow){state.follow=false;document.getElementById('followObject').textContent='◎ Seguir objeto'}else{state.follow=true;document.getElementById('followObject').textContent='◎ Parar de seguir'}};document.getElementById('scanObject').onclick=()=>{if(!state.selected)return;discovered.add(state.selected.userData.name);document.getElementById('missionText').textContent=`✓ ${state.selected.userData.name} registrado. ${discovered.size} descoberta(s).`;document.getElementById('scanObject').textContent='✓ Registrado';setTimeout(()=>document.getElementById('scanObject').textContent='◉ Escanear objeto',1000)};
select(sun);reset();cameraUpdate();
function animate(t){requestAnimationFrame(animate);const dt=Math.min(3,(t-(animate.last||t))/16.67);animate.last=t;if(!state.paused){sun.rotation.y+=.002*state.speed*dt;planets.forEach(p=>{p.userData.angle+=p.userData.velocity*state.speed*dt;p.position.set(Math.cos(p.userData.angle)*p.userData.orbit,0,Math.sin(p.userData.angle)*p.userData.orbit);p.rotation.y+=.006*state.speed*dt});const a=t*.001*state.speed;moon.position.set(earth.position.x+Math.cos(a)*1.8,.1,earth.position.z+Math.sin(a)*1.8);cometAngle+=.004*state.speed*dt;comet.position.set(Math.cos(cometAngle)*32,Math.sin(cometAngle*2)*1.8,Math.sin(cometAngle)*32);cometGlow.position.copy(comet.position);galaxy.rotation.y+=.00004*state.speed*dt;asteroidBelt.rotation.y+=.0007*state.speed*dt}labels.forEach(l=>{const o=l.userData.target;if(o){l.position.copy(o.position);l.position.y+=o.geometry.parameters.radius+.75}});if(state.follow&&state.selected)state.target.lerp(state.selected.position,.12);cameraUpdate();renderer.render(scene,camera)}
requestAnimationFrame(animate);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
setTimeout(()=>loading.classList.add('hidden'),900);